plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
    id 'maven-publish'
}

version = System.getenv('MOD_VERSION') ?: '1.0.0'
group = 'dev.damagetilt'

base {
    archivesName = 'damagetilt'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${System.getenv('MC_VERSION') ?: '1.21.4'}"
    mappings "net.fabricmc:yarn:${System.getenv('YARN_VERSION') ?: '1.21.4+build.1'}:v2"
    modImplementation 'net.fabricmc:fabric-loader:0.16.9'
    modImplementation "net.fabricmc.fabric-api:fabric-api:${System.getenv('FABRIC_API') ?: '0.119.2+1.21.4'}"
}

processResources {
    inputs.property 'version', project.version
    filteringCharset 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
